algoritmo "semnome"
// Função :
// Autor :
// Data : 08/09/2024
// Seção de Declarações 
var
a, b:inteiro
abd: real
inicio
// Seção de Comandos 
escreval("***Calcular o quadrado da diferença")
escreval("Digite o valor de A: ")
leia(a)
escreval("Digite o valor de B: ")
leia(b)

abd := (a - b)^2

escreval("")
escreval("RESULTADO")
escreval("  O resultado do quadrado da diferença do primeiro valor pelo segundo é:",abd)





fimalgoritmo
